import { Movie } from './movie';
export const MOVIES: Movie[]=[
  {"title":"A New Hope","episode_id":4,"producer":"Stan Lee","director":"James EarlWorth","release_date":"10 June 1992","opening_crawl":"It is a period of civil war In the end of this project, the bank will have a large following and their new system will be used by a large number of users who will join the bank as clients. My team will develop a project management plan, make a work .\r\nRebel"},
  {"title":"The Empire Strikes back","episode_id":5,"producer":"Stan Lee","director":"James EarlWorth","release_date":"10 June 1994","opening_crawl":"Its a dark time the jedi In the end of this project, the bank will have a large following and their new system will be used by a large number of users who will join the bank as clients. My team will develop a project management plan, make a work .\r\nRebel"},
  {"title":"Return of the Jedi","episode_id":6,"producer":"Stan Lee","director":"James EarlWorth","release_date":"10 June 1997","opening_crawl":"luke Skywalker has returned In the end of this project, the bank will have a large following and their new system will be used by a large number of users who will join the bank as clients. My team will develop a project management plan, make a work .\r\nRebel"},
  {"title":"The phantom Menace","episode_id":1,"producer":"Stan Lee","director":"James EarlWorth","release_date":"10 June 1999","opening_crawl":"Turmoil has engulfed theIn the end of this project, the bank will have a large following and their new system will be used by a large number of users who will join the bank as clients. My team will develop a project management plan, make a work . \r\nRebel"},
  {"title":"Attack of the Clones","episode_id":2,"producer":"Stan Lee","director":"James EarlWorth","release_date":"10 June 2002","opening_crawl":"There is unrest in the Galaxy In the end of this project, the bank will have a large following and their new system will be used by a large number of users who will join the bank as clients. My team will develop a project management plan, make a work .\r\nRebel"},
  {"title":"Revenge of the Sixth","episode_id":3,"producer":"Stan Lee","director":"James EarlWorth","release_date":"10 June 2006","opening_crawl":"The republic is crumbling In the end of this project, the bank will have a large following and their new system will be used by a large number of users who will join the bank as clients. My team will develop a project management plan, make a work .\r\nRebel"},
  {"title":"The force awakens","episode_id":7,"producer":"Stan Lee","director":"James EarlWorth","release_date":"10 June 2009","opening_crawl":"Luke Skywalker has vanished leaving the empire to In the end of this project, the bank will have a large following and their new system will be used by a large number of users who will join the bank as clients. My team will develop a project management plan, make a work .\r\nRebel"}
];